parameters:
    google_maps_api_key: '%env(GOOGLE_MAPS_API_KEY)%'
    csv_directory: '%kernel.project_dir%/public/uploads/csv'

services:
    _defaults:
        autowire: true      # Injection automatique des dépendances
        autoconfigure: true # Enregistre automatiquement les subscribers

    App\Repository\:
        resource: '../src/Repository'
        autowire: true
        autoconfigure: true

    # Rend toutes les classes dans src/ disponibles en tant que services, sauf exclusions
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Définition explicite du service GeolocationService
    App\Service\GeolocationService:
        arguments:
            $googleMapsApiKey: '%google_maps_api_key%'
